<?php
/**
 * @file
 * Code for the GSB Feature Featured Insight Card FPP feature.
 */

include_once 'gsb_feature_featured_insight_card_fpp.features.inc';

/**
 * Implements hook_entity_alter().
 */
function gsb_feature_featured_insight_card_fpp_entity_info_alter(&$entity_info) {
  $entity_info['fieldable_panels_pane']['bundles']['featured_insight_card'] = array(
    'label' => t('Featured Insight Card'),
    'pane category' => t('GSB panes'),
    'pane top level' => TRUE, // set to true to make this show as a top level icon
    'pane icon' => drupal_get_path('module', 'panopoly_widgets') . '/images/icon_text.png',
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      // Note that this has all _ replaced with - from the bundle name.
      'real path' => 'admin/structure/fieldable-panels-panes/manage/featured-insight-card',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );
}

/**
 * Implements hook_form_alter().
 *  - Set defaults for Featured Insight Card fpp form. 
 */
function gsb_feature_featured_insight_card_fpp_form_alter(&$form, &$form_state) {
  if (in_array($form['#form_id'], array(
      'fieldable_panels_panes_entity_edit_form',
      'fieldable_panels_panes_fieldable_panels_pane_content_type_edit_form',
    )) && $form['#bundle'] == 'featured_insight_card') {

    // Hide reusable checkbox instead of #access = FALSE to preserve fieldset display.
    $form['reusable']['reusable']['#attributes']['style'] = 'display:none;';
    $form['reusable']['reusable']['#suffix'] = t('This FPP is reusable and can\'t be changed');
    $form['reusable']['reusable']['#value'] = 1;

    $form['reusable']['admin_title']['#default_value'] = !empty($form['reusable']['admin_title']['#default_value']) ? $form['reusable']['admin_title']['#default_value'] : t('Featured Insight Card item: ');
    $form['reusable']['category']['#default_value'] = !empty($form['reusable']['category']['#default_value']) ? $form['reusable']['category']['#default_value'] : 'Marketing'; 
  }
}
